package com.hashtagchow.magehand.core.data.catalog

import com.hashtagchow.magehand.core.model.NewLocalRowSpec
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The bundled catalogs, pinned against their own provenance record (FR-49,
 * docs/design/20-local-spells-and-attacks.md decision 7).
 *
 * ### What this test is FOR, stated because it looks like it is testing a parser
 *
 * It is not. The parser is `kotlinx.serialization` and it needs no help. What is pinned here is
 * that **the data the app ships is the data the repository says it ships** — the edition, the
 * counts, the licence, and a handful of entries quoted by hand off the source. Decision 7 asks for
 * exactly that: *"exact source URL, version / commit, retrieval date, licence, and entry counts …
 * are **pinned by test**: counts, a handful of spot-checked entries by id, and the higher-level
 * paragraph on a known upcasting spell"*.
 *
 * The reason is the `ContractExportTest` lesson, one directory along: a bundled data file is the
 * one thing in a repository that can be silently regenerated by somebody being helpful. A
 * re-fetch that changed an edition, dropped a field, or quietly normalised the SRD's punctuation
 * would otherwise be invisible until a player noticed that Fireball no longer upcasts.
 *
 * **A failure here is not a licence to update the numbers.** Re-fetching means re-recording:
 * `provenance.json` gets the new commit and the new date, and the spot-checks below are re-read
 * against the new source by a human, exactly as re-recording a golden means eyeballing the diff.
 */
class CatalogTest {

    // --- counts, against the record rather than against a literal ------------

    /**
     * The count the file holds and the count the record claims are the same number.
     *
     * Asserted **against `provenance.json`** rather than against `319` written here, so that the
     * two things a re-fetch has to update stay one edit apart: change the data without changing
     * the record and this fails; change both and it passes, which is the state the repository is
     * supposed to be in. The literal below is the third leg, and it is what stops both being
     * changed by accident — a 319 that became 3 would satisfy the first assertion.
     */
    @Test
    fun `the spell catalog holds exactly what its provenance record claims`() {
        assertEquals(CatalogProvenance.spells.entryCount, SpellCatalog.entries.size)
        assertEquals(319, SpellCatalog.entries.size)
        assertEquals("SRD 5.1", CatalogProvenance.spells.edition)
        assertEquals("CC-BY-4.0", CatalogProvenance.spells.contentLicence)
    }

    @Test
    fun `the weapon catalog holds exactly what its provenance record claims`() {
        assertEquals(CatalogProvenance.weapons.entryCount, WeaponCatalog.entries.size)
        assertEquals(38, WeaponCatalog.entries.size)
        assertEquals("SRD 5.2.1", CatalogProvenance.weapons.edition)
        assertEquals("CC-BY-4.0", CatalogProvenance.weapons.contentLicence)
    }

    /**
     * **The editions are not mixed inside a file** — decision 7's fence, as a property rather than
     * as a promise.
     *
     * The two catalogs are from different editions, which decision 7 permits and the record
     * states. What it forbids is blending, and the observable form of that here is the 2024-only
     * weapon mastery: if a 5.1 weapon had been folded into the 2024 list it would carry none, and
     * if a 2024 spell had been folded into the 5.1 list there would be no way to tell — which is
     * why the weapon side is the one that can be checked, and is checked.
     */
    @Test
    fun `every weapon carries the 2024 mastery its edition is claimed for`() {
        val missing = WeaponCatalog.entries.filter { it.mastery.isNullOrBlank() }
        assertTrue(
            "a weapon with no mastery would be a 5.1 entry in a 5.2.1 file: ${missing.map { it.id }}",
            missing.isEmpty(),
        )
    }

    /** CC-BY's own requirement: there is an attribution sentence, and it names the edition. */
    @Test
    fun `each catalog carries an attribution sentence naming its SRD edition`() {
        assertTrue(CatalogProvenance.spells.attribution.contains("SRD 5.1"))
        assertTrue(CatalogProvenance.spells.attribution.contains("Creative Commons Attribution"))
        assertTrue(CatalogProvenance.weapons.attribution.contains("SRD 5.2.1"))
        assertTrue(CatalogProvenance.weapons.attribution.contains("Creative Commons Attribution"))
    }

    /**
     * The sentence is **complete on its own**, because Settings prints it and nothing else.
     *
     * M2 [review, 2026-09-12]. CC-BY-4.0 §3(a)(1) asks the attribution to carry a URI for the
     * licence (A)(iv) and to *"indicate if You modified the Licensed Material"* (B). Both used to
     * sit in `provenance.json` as separate fields that no screen read, beside a sentence the app
     * then paraphrased in `strings.xml`. They are in the sentence now, and this is what stops a
     * later edit quietly taking either one back out: the URL asserted against the record's own
     * `contentLicenceUrl` rather than against a literal, so the two cannot drift.
     */
    @Test
    fun `each attribution sentence carries the licence URL and says the material was modified`() {
        listOf(CatalogProvenance.spells, CatalogProvenance.weapons).forEach { source ->
            assertTrue(
                "${source.edition}: no licence URL in the printed sentence",
                source.attribution.contains(source.contentLicenceUrl),
            )
            assertTrue(
                "${source.edition}: no CC-BY 3(a)(1)(B) modification statement",
                source.attribution.contains("modified"),
            )
        }
    }

    /**
     * The abbreviation is introduced once and never doubled — NIT 4 [review, 2026-09-12].
     *
     * Settings used to read *"System Reference Documents SRD 5.1 and SRD 5.2.1"*, because the
     * screen's own sentence said "System Reference Documents" and then substituted the record's
     * `edition`, which already says "SRD". The screen prints these sentences verbatim now, so the
     * wording is the record's; this is the assertion that the record's wording is right.
     */
    @Test
    fun `no attribution sentence doubles the SRD abbreviation`() {
        listOf(CatalogProvenance.spells, CatalogProvenance.weapons).forEach { source ->
            assertFalse(
                "\"Documents SRD\" reads as \"SRD SRD\": ${source.attribution}",
                source.attribution.contains("Document SRD") ||
                    source.attribution.contains("Documents SRD"),
            )
        }
    }

    // --- shape --------------------------------------------------------------

    /**
     * Every entry is renderable and addressable: no blank name, no blank description, no duplicate
     * id, every level inside the range the form validates.
     *
     * The duplicate check is the one worth stating: `byId` is an index, so two entries sharing an
     * id would silently make one of them unreachable — the picker would list it and the tap would
     * fill the form with the other one's text.
     */
    @Test
    fun `every spell is addressable, named and described`() {
        assertEquals(
            "duplicate ids would make one entry unreachable through byId",
            SpellCatalog.entries.size,
            SpellCatalog.entries.map { it.id }.toSet().size,
        )
        SpellCatalog.entries.forEach { spell ->
            assertTrue("blank name: ${spell.id}", spell.name.isNotBlank())
            assertTrue("blank description: ${spell.id}", spell.description.isNotBlank())
            assertTrue(
                "level out of range: ${spell.id} = ${spell.level}",
                spell.level in NewLocalRowSpec.SPELL_LEVELS,
            )
        }
    }

    @Test
    fun `every weapon is addressable, named and carries its damage as text`() {
        assertEquals(
            WeaponCatalog.entries.size,
            WeaponCatalog.entries.map { it.id }.toSet().size,
        )
        WeaponCatalog.entries.forEach { weapon ->
            assertTrue("blank name: ${weapon.id}", weapon.name.isNotBlank())
            assertTrue("blank damage: ${weapon.id}", weapon.damage.isNotBlank())
            assertTrue("blank category: ${weapon.id}", weapon.category.isNotBlank())
        }
    }

    /**
     * The per-level histogram, whole.
     *
     * A count alone would survive a re-fetch that dropped every 9th-level spell and gained fifteen
     * cantrips. This is the shape of the list rather than its size, and it is the cheapest thing
     * that would catch a subset being taken.
     */
    @Test
    fun `the spell list has the shape the SRD 5_1 list has`() {
        assertEquals(
            mapOf(
                0 to 24, 1 to 49, 2 to 54, 3 to 42, 4 to 31,
                5 to 37, 6 to 31, 7 to 20, 8 to 16, 9 to 15,
            ),
            SpellCatalog.entries.groupingBy { it.level }.eachCount(),
        )
    }

    /** Level ascending then name — the order the picker scans in. See `SpellCatalog.entries`. */
    @Test
    fun `the spell list is sorted by level then name`() {
        val keys = SpellCatalog.entries.map { it.level to it.name }
        assertEquals(keys.sortedWith(compareBy({ it.first }, { it.second })), keys)
    }

    // --- spot-checks, quoted off the source ---------------------------------

    /**
     * Fireball, field by field — decision 7's *"a handful of spot-checked entries by id"*, and the
     * named example of *"the higher-level paragraph on a known upcasting spell"*.
     *
     * The components string is asserted **with the source's own capitalisation and trailing full
     * stop** (*"(A tiny ball of bat guano and sulfur.)"*), which reads like a typo and is not one:
     * a verbatim reproduction is verbatim or it is an edit nobody recorded. `provenance.json`'s
     * `derivationNote` says the same thing in prose; this is the half that fails.
     */
    @Test
    fun `fireball is the SRD's fireball, upcast paragraph included`() {
        val fireball = SpellCatalog.byId("fireball")!!
        assertEquals("Fireball", fireball.name)
        assertEquals(3, fireball.level)
        assertEquals("Evocation", fireball.school)
        assertEquals("1 action", fireball.castingTime)
        assertEquals("150 feet", fireball.range)
        assertEquals("V, S, M (A tiny ball of bat guano and sulfur.)", fireball.components)
        assertEquals("Instantaneous", fireball.duration)
        assertFalse(fireball.concentration)
        assertFalse(fireball.ritual)
        assertEquals(
            "When you cast this spell using a spell slot of 4th level or higher, the damage " +
                "increases by 1d6 for each slot level above 3rd.",
            fireball.higherLevels,
        )
        assertEquals(listOf("Sorcerer", "Wizard"), fireball.classes)
    }

    /** The second upcasting spell decision 7 names, and a third for good measure. */
    @Test
    fun `cure wounds and magic missile carry their own upcast paragraphs`() {
        assertEquals(
            "When you cast this spell using a spell slot of 2nd level or higher, the healing " +
                "increases by 1d8 for each slot level above 1st.",
            SpellCatalog.byId("cure-wounds")!!.higherLevels,
        )
        assertEquals(1, SpellCatalog.byId("cure-wounds")!!.level)
        assertEquals(
            "When you cast this spell using a spell slot of 2nd level or higher, the spell " +
                "creates one more dart for each slot level above 1st.",
            SpellCatalog.byId("magic-missile")!!.higherLevels,
        )
    }

    /**
     * A spell with **no** upcast paragraph reads as `null`, not as an empty string.
     *
     * The distinction is the whole of 20 decision 5's *"a spell with no such paragraph shows no
     * heading"*: an empty string would draw the heading over nothing, which is this app reporting
     * on the SRD's completeness rather than on the spell. 229 of the 319 are in this state, so it
     * is the common case rather than an edge one.
     */
    @Test
    fun `a spell that does not upcast has a null paragraph and not a blank one`() {
        val light = SpellCatalog.byId("light")!!
        assertEquals(0, light.level)
        assertFalse(light.ritual)
        assertNull(light.higherLevels)
        assertEquals(
            "most spells do not upcast",
            229,
            SpellCatalog.entries.count { it.higherLevels == null },
        )
        assertTrue(
            "an empty string would draw the heading over nothing",
            SpellCatalog.entries.none { it.higherLevels?.isBlank() == true },
        )
    }

    /**
     * Three weapons, whole — including the versatile damage string and the mastery word that
     * FR-47's badge is built from.
     */
    @Test
    fun `longsword, dagger and shortbow are the SRD's`() {
        with(WeaponCatalog.byId("longsword")!!) {
            assertEquals("Longsword", name)
            assertEquals("Martial Melee", category)
            assertEquals("1d8 / 1d10 slashing", damage)
            assertEquals(listOf("Versatile (1d10)"), properties)
            assertEquals("Sap", mastery)
            assertEquals(3.0, weightLb)
            assertEquals(15.0, costGp)
        }
        with(WeaponCatalog.byId("dagger")!!) {
            assertEquals("Simple Melee", category)
            assertEquals("1d4 piercing", damage)
            assertEquals(listOf("Finesse", "Light", "Thrown (Range 20/60)"), properties)
            assertEquals("Nick", mastery)
        }
        with(WeaponCatalog.byId("shortbow")!!) {
            assertEquals("Simple Ranged", category)
            assertEquals("1d6 piercing", damage)
            assertEquals(
                listOf("Ammunition (Range 80/320; Arrows)", "Two-Handed"),
                properties,
            )
            assertEquals("Vex", mastery)
        }
    }

    @Test
    fun `an id this build does not carry resolves to null rather than throwing`() {
        assertNull(SpellCatalog.byId("wish-for-a-pony"))
        assertNull(WeaponCatalog.byId("plot-device"))
        assertNotNull(SpellCatalog.byId("fireball"))
    }

    // --- search -------------------------------------------------------------

    /**
     * The picker's filter: case-insensitive substring of the **name**, and a blank query returns
     * everything.
     *
     * Name-only is asserted through a word that appears in a great many descriptions and in no
     * name at all — if the search ever widened to the description, *"damage"* would return dozens
     * of spells to a player who typed it expecting one.
     */
    @Test
    fun `search matches names case-insensitively and never descriptions`() {
        assertEquals(
            // A *substring*, not a prefix — "Delayed Blast Fireball" is a match, and a player
            // typing a word they half-remember should find it.
            listOf("Fireball", "Delayed Blast Fireball"),
            SpellCatalog.search("fireBALL").map { it.name },
        )
        assertTrue(SpellCatalog.search("  ").size == SpellCatalog.entries.size)
        assertTrue(
            "a description search would make this non-empty",
            SpellCatalog.search("bat guano").isEmpty(),
        )
        assertEquals(
            listOf("Greatsword", "Longsword", "Shortsword"),
            WeaponCatalog.search("sword").map { it.name }.sorted(),
        )
    }

    // --- the catalog as a template (20 decision 6) --------------------------

    /**
     * A catalog pick becomes a **spec**, and the spec is valid — which is what lets decision 6's
     * pre-filled form open on something saveable rather than on something already red.
     *
     * The `school` and `classes` assertions are negative on purpose: they are *not* carried onto
     * the row, and `NewLocalRowSpec.ofSpell`'s KDoc says why. A future reader adding them should
     * have to delete a line that states the decision.
     */
    @Test
    fun `a catalog spell becomes a valid spec carrying the text and not the taxonomy`() {
        val spec = NewLocalRowSpec.ofSpell(SpellCatalog.byId("fireball")!!)

        assertTrue(spec.isValid)
        assertEquals("Fireball", spec.label)
        assertEquals(3, spec.spellLevel)
        assertEquals("fireball", spec.catalogId)
        assertEquals("150 feet", spec.range)
        assertTrue(spec.higherLevels!!.startsWith("When you cast this spell"))
        assertEquals("uses are the player's to add, not the SRD's", 0, spec.uses)
        assertNull("a weapon field has no place on a spell", spec.damage)
        assertNull(spec.properties)
    }

    /**
     * A catalog weapon becomes a spec whose `properties` string carries the mastery as a term —
     * the single source FR-47's badge is read back out of (`LocalActionBoard.masteryFrom`).
     */
    @Test
    fun `a catalog weapon folds its mastery into the editable property string`() {
        val spec = NewLocalRowSpec.ofAttack(WeaponCatalog.byId("longsword")!!)

        assertTrue(spec.isValid)
        assertEquals("Longsword", spec.label)
        assertEquals("1d8 / 1d10 slashing", spec.damage)
        assertEquals("Versatile (1d10), Mastery: Sap", spec.properties)
        assertEquals("longsword", spec.catalogId)
        assertNull("an attack states no level", spec.spellLevel)
    }

    /** Every catalog entry produces a saveable spec — no entry is un-addable. */
    @Test
    fun `every catalog entry produces a valid spec`() {
        assertTrue(SpellCatalog.entries.all { NewLocalRowSpec.ofSpell(it).isValid })
        assertTrue(WeaponCatalog.entries.all { NewLocalRowSpec.ofAttack(it).isValid })
    }
}
